CREATE TABLE STG_DATA_CORRECTION
(
  FUNDING_YEAR        NUMBER(4),
  SCIO_STUDENT_NBR    NUMBER(6),
  SURNAME             VARCHAR2(60 BYTE),
  FIRST_NAME          VARCHAR2(60 BYTE),
  DOB                 DATE,
  GENDER              VARCHAR2(1 BYTE),
  SCHOOL_GRADE        VARCHAR2(20 BYTE),
  SCHOOL_NAME_SUBURB  VARCHAR2(100 BYTE),
  SWD2_APPL_ID        VARCHAR2(50 BYTE),
  WASN                NUMBER(8),
  PROC_IND            VARCHAR2(1 BYTE)          DEFAULT 'N',
  ERR_DATE            DATE,
  ERR_MESSAGE         VARCHAR2(1000 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
