CREATE TABLE STG_APPLICATION_2021_ERR
(
  ORA_ERR_NUMBER$    NUMBER,
  ORA_ERR_MESG$      VARCHAR2(2000 BYTE),
  ORA_ERR_ROWID$     UROWID(4000),
  ORA_ERR_OPTYP$     VARCHAR2(2 BYTE),
  ORA_ERR_TAG$       VARCHAR2(2000 BYTE),
  APPL_STUDENT_ID    VARCHAR2(4000 BYTE),
  FUNDING_YEAR       VARCHAR2(4000 BYTE),
  DISABLING_COND_ID  VARCHAR2(4000 BYTE),
  MIGRATED_IND       VARCHAR2(4000 BYTE),
  ERR_DATE           VARCHAR2(4000 BYTE),
  ERR_DESC           VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
