CREATE TABLE SUB_DISABILITY_CATEGORIES
(
  ID             NUMBER(7),
  DIS_CAT_ID     VARCHAR2(10 BYTE),
  SUB_CAT_ID     VARCHAR2(20 BYTE),
  DESCRIPTION    VARCHAR2(250 BYTE),
  EFF_FROM_DATE  DATE,
  EFF_TO_DATE    DATE,
  CREATED_BY     VARCHAR2(100 BYTE),
  CREATED_DATE   DATE,
  LAST_UPD_BY    VARCHAR2(100 BYTE),
  LAST_UPD_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
