CREATE TABLE SWD_CODES
(
  SWD_CODE_ID        NUMBER(9),
  SWD_CODE_TYPE      VARCHAR2(10 BYTE),
  SWD_CODE           VARCHAR2(20 BYTE),
  SHORT_DESCRIPTION  VARCHAR2(250 BYTE),
  LONG_DESCRIPTION   VARCHAR2(2000 BYTE),
  EFF_FROM_DATE      DATE,
  EFF_TO_DATE        DATE,
  SORT_ORDER         NUMBER(4),
  CREATED_BY         VARCHAR2(100 BYTE),
  CREATED_DATE       DATE,
  LAST_UPD_BY        VARCHAR2(100 BYTE),
  LAST_UPD_DATE      DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
