CREATE TABLE SWD_STATE_PER_CAPITA_RATE
(
  SPC_RATE_ID          NUMBER(7),
  FUNDING_YEAR         NUMBER(4),
  FUNDING_TYPE         VARCHAR2(1 BYTE),
  STATE_FUNDING_CATGY  VARCHAR2(10 BYTE),
  KINDY_AMT            NUMBER(12,2)             DEFAULT ON NULL 0.00,
  KINDY_FUNDED_FLG     VARCHAR2(1 BYTE)         DEFAULT ON NULL 'N',
  PRIMARY_AMT          NUMBER(12,2)             DEFAULT ON NULL 0.00,
  MIDDLE_AMT           NUMBER(12,2)             DEFAULT ON NULL 0.00,
  SECONDARY_AMT        NUMBER(12,2)             DEFAULT ON NULL 0.00,
  CREATED_BY           VARCHAR2(100 BYTE),
  CREATED_DATE         DATE,
  LAST_UPD_BY          VARCHAR2(100 BYTE),
  LAST_UPD_DATE        DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
