CREATE TABLE SWD_NOTIFICATION_LOG
(
  NOTIF_ID           NUMBER(9),
  NOTIF_TYPE         VARCHAR2(50 BYTE),
  NOTIF_SOURCE       VARCHAR2(30 BYTE),
  SOURCE_REC_ID_NUM  NUMBER(16),
  SOURCE_REC_ID_CHR  VARCHAR2(16 BYTE),
  SOURCE_REC_ID_COL  VARCHAR2(30 BYTE),
  NOTIF_DATE         DATE,
  NOTIF_RECIPIENTS   VARCHAR2(1000 BYTE),
  NOTIF_COMMENT      VARCHAR2(1000 BYTE),
  ERR_DATE           DATE,
  ERR_TEXT           VARCHAR2(1000 BYTE),
  CREATED_BY         VARCHAR2(100 BYTE),
  CREATED_DATE       DATE,
  LAST_UPD_BY        VARCHAR2(100 BYTE),
  LAST_UPD_DATE      DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
