CREATE TABLE SWD_CONSULTANT_SCHOOL
(
  CONSULT_SCHOOL_ID  NUMBER(7),
  EMPLOYEE#          VARCHAR2(8 BYTE),
  SCHOOL_ID          NUMBER(7),
  EFF_FROM_DATE      DATE,
  EFF_TO_DATE        DATE,
  CREATED_BY         VARCHAR2(100 BYTE),
  CREATED_DATE       DATE,
  LAST_UPD_BY        VARCHAR2(100 BYTE),
  LAST_UPD_DATE      DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
