CREATE TABLE SWD_DOCUMENT
(
  DOC_ID           NUMBER(9),
  UNIQUE_DOC_NAME  VARCHAR2(400 BYTE),
  FILENAME         VARCHAR2(400 BYTE),
  MIME_TYPE        VARCHAR2(255 BYTE),
  BLOB_CONTENT     BLOB,
  BLOB_SIZE        NUMBER,
  DOC_COMMENT      VARCHAR2(4000 BYTE),
  DELETE_DATE      DATE,
  CREATED_BY       VARCHAR2(100 BYTE),
  CREATED_DATE     DATE,
  LAST_UPD_BY      VARCHAR2(100 BYTE),
  LAST_UPD_DATE    DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
