CREATE TABLE SWD_APPL_DOCUMENT_20210815
(
  APPL_ID        NUMBER(9),
  DOC_ID         NUMBER(9),
  DOC_HIDE_DATE  DATE,
  CREATED_BY     VARCHAR2(100 BYTE),
  CREATED_DATE   DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
