CREATE TABLE SWD_DOC_ACCESS_LOG
(
  DOC_ID         NUMBER(9),
  ACCESSED_BY    VARCHAR2(30 BYTE),
  ACCESSED_DATE  DATE, 
  CONSTRAINT SWD_DOC_ACCESS_LOG_PK
  PRIMARY KEY
  (DOC_ID, ACCESSED_BY, ACCESSED_DATE)
  ENABLE VALIDATE
)
ORGANIZATION INDEX
PCTTHRESHOLD 50
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
