CREATE TABLE SWD_GRANT
(
  SWD_GRANT_ID   NUMBER(7),
  GRANT_YEAR     NUMBER(4),
  REC_TYPE       VARCHAR2(1 BYTE),
  SCHOOL_ID      NUMBER(7),
  APPL_ID        NUMBER(9),
  REQUEST_AMT    NUMBER(12,2),
  ACTUAL_AMT     NUMBER(12,2),
  PURPOSE        VARCHAR2(150 BYTE),
  GRANT_TYPE     VARCHAR2(1 BYTE),
  PAID_DATE      DATE,
  GRANT_COMMENT  VARCHAR2(200 BYTE),
  DELETE_DATE    DATE,
  CREATED_BY     VARCHAR2(100 BYTE),
  CREATED_DATE   DATE,
  LAST_UPD_BY    VARCHAR2(100 BYTE),
  LAST_UPD_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
