CREATE TABLE TEMP_SWD2_POST_PROCESSING_CHANGES_DELETES_ACTIVE_INACTIVE_AUG_2022
(
  SCHOOL      VARCHAR2(100 BYTE),
  CONSULTANT  VARCHAR2(50 BYTE),
  STUDENT     VARCHAR2(50 BYTE),
  APP_ID      NUMBER,
  ACTION      VARCHAR2(56 BYTE),
  LVL         VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
