CREATE TABLE TEMP_NEW_SEMESTER_2_STUDENTS_2022
(
  SCHOOL         VARCHAR2(100 BYTE),
  CONSULTANT     VARCHAR2(50 BYTE),
  STUDENT        VARCHAR2(50 BYTE),
  YEAR_LEVEL_22  NUMBER,
  APP_ID         NUMBER,
  ACTION         VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
