CREATE TABLE WASN_PART1
(
  APPL_ID                         NUMBER,
  FUNDING_YEAR                    NUMBER,
  STATE_STUDENT_NBR               VARCHAR2(30 BYTE),
  STUDENT_USERNAME                VARCHAR2(450 BYTE),
  WASN                            NUMBER,
  STUDENT_FIRST_NAME              VARCHAR2(50 BYTE),
  STUDENT_SURNAME                 VARCHAR2(50 BYTE),
  DOB                             DATE,
  GENDER                          VARCHAR2(6 BYTE),
  RELIGION_CODE                   VARCHAR2(30 BYTE),
  SCHOOL_ID                       NUMBER,
  ENROLLED_SCHOOL_LVL             VARCHAR2(30 BYTE),
  FUNDING_SCHOOL_LVL              VARCHAR2(30 BYTE),
  PARENT_CONSENT_FLG              VARCHAR2(30 BYTE),
  APPL_ADJ_LVL_CODE               NUMBER,
  APPL_ADJ_LVL_COMMENT            VARCHAR2(500 BYTE),
  NCCD_CATGY_CODE                 VARCHAR2(40 BYTE),
  NCCD_ADJ_LVL_CODE               VARCHAR2(40 BYTE),
  IAP_CURRIC_PARTCP_COMMENT       VARCHAR2(4000 BYTE),
  IAP_CURRIC_PARTCP_ADJ_LVL_CODE  VARCHAR2(50 BYTE),
  IAP_COMMUN_PARTCP_COMMENT       VARCHAR2(4000 BYTE),
  IAP_COMMUN_PARTCP_ADJ_LVL_CODE  VARCHAR2(50 BYTE),
  IAP_MOBILITY_COMMENT            VARCHAR2(4000 BYTE),
  IAP_MOBILITY_ADJ_LVL_CODE       VARCHAR2(50 BYTE),
  IAP_PERSONAL_CARE_COMMENT       VARCHAR2(4000 BYTE),
  IAP_PERSONAL_CARE_ADJ_LVL_CODE  VARCHAR2(50 BYTE),
  IAP_SOC_SKILLS_COMMENT          VARCHAR2(4000 BYTE),
  IAP_SOC_SKILLS_ADJ_LVL_CODE     VARCHAR2(50 BYTE),
  IAP_SAFETY_COMMENT              VARCHAR2(4000 BYTE),
  IAP_SAFETY_ADJ_LVL_CODE         VARCHAR2(50 BYTE),
  DELETE_DATE                     VARCHAR2(11 BYTE),
  VERSION_NBR                     NUMBER,
  RELATED_APPL_ID                 VARCHAR2(50 BYTE),
  CREATED_BY                      VARCHAR2(100 BYTE),
  CREATED_DATE                    DATE,
  LAST_UPD_BY                     VARCHAR2(100 BYTE),
  LAST_UPD_DATE                   DATE,
  INACTIVE_DATE                   VARCHAR2(30 BYTE),
  REVIEW_DATE                     VARCHAR2(30 BYTE),
  REVIEW_COMMENT                  VARCHAR2(4000 BYTE),
  STUDENT_FTE                     NUMBER,
  FED_GOVT_FUNDING_EXCL_FLG       VARCHAR2(50 BYTE),
  LEGACY_STUDENT_ID               VARCHAR2(17 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
